USE [master]
GO

/****** Object:  Database [ShopQuanAo]    Script Date: 8/25/2022 11:20:19 AM ******/
CREATE DATABASE [ShopQuanAo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ShopQuanAo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.VGS\MSSQL\DATA\ShopQuanAo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ShopQuanAo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.VGS\MSSQL\DATA\ShopQuanAo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ShopQuanAo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ShopQuanAo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ShopQuanAo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ShopQuanAo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ShopQuanAo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ShopQuanAo] SET ARITHABORT OFF 
GO

ALTER DATABASE [ShopQuanAo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ShopQuanAo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ShopQuanAo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ShopQuanAo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ShopQuanAo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ShopQuanAo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ShopQuanAo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ShopQuanAo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ShopQuanAo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ShopQuanAo] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ShopQuanAo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ShopQuanAo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ShopQuanAo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ShopQuanAo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ShopQuanAo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ShopQuanAo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ShopQuanAo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ShopQuanAo] SET RECOVERY FULL 
GO

ALTER DATABASE [ShopQuanAo] SET  MULTI_USER 
GO

ALTER DATABASE [ShopQuanAo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ShopQuanAo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ShopQuanAo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ShopQuanAo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ShopQuanAo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ShopQuanAo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ShopQuanAo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ShopQuanAo] SET  READ_WRITE 
GO

