//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartInfo
    {
        public int IDCARTINFO { get; set; }
        public Nullable<int> IDCART { get; set; }
        public Nullable<int> IDPRODUCT { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string MESSAGER { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
