//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cart()
        {
            this.CartInfoes = new HashSet<CartInfo>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDACC { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public string DIACHI { get; set; }
        public string SIZESP { get; set; }
        public int STATUSS { get; set; }
        public Nullable<int> IdProducrt { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartInfo> CartInfoes { get; set; }
    }
}
