//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageProduct
    {
        public int IDIMAGE { get; set; }
        public Nullable<int> IDPRODUCT { get; set; }
        public string LINK { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
