//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CartInfoes = new HashSet<CartInfo>();
            this.ImageProducts = new HashSet<ImageProduct>();
        }
    
        public int IDPRODUCT { get; set; }
        public string NAMEPRODUCT { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<int> RRICESALE { get; set; }
        public Nullable<bool> STATUSS { get; set; }
        public Nullable<bool> SEX { get; set; }
        public string DESCRIPTIONS { get; set; }
        public string IMAGELINK { get; set; }
        public Nullable<int> IDCATEGORY { get; set; }
        public Nullable<int> LIKES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartInfo> CartInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageProduct> ImageProducts { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
